-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDQLEHhgMQLT5Ft6d
kkCQTSYyMpUfvOiSNIXaeG3GMkigCgYIKoZIzj0DAQehRANCAASJDuhrCBPSuTZQ
iImoonWH9/TLPgs84R3zN1M4ZbvZwJS1PTiUnPe9Dxg0yOVKWDIlUSYM99JCUx7l
Q77nn7cH
-----END PRIVATE KEY-----